apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: webserver
    spec:
      containers:
      - name: webserver
        image: nginx:stable
